// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDN2UopnAGZRlbsDe91fSLTXgftoj5Et4',
    appId: '1:333781022432:android:3a71bb6fe1b71e27b74285',
    messagingSenderId: '333781022432',
    projectId: 'performai-d58f4',
    storageBucket: 'performai-d58f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBSA2-avcZNZvcUQTzpcsKPFsnjW6wgRE',
    appId: '1:333781022432:ios:cf0685a7820e21d5b74285',
    messagingSenderId: '333781022432',
    projectId: 'performai-d58f4',
    storageBucket: 'performai-d58f4.firebasestorage.app',
    androidClientId: '333781022432-ilkvg2l6gkdlogmasndn171haojvfpv6.apps.googleusercontent.com',
    iosClientId: '333781022432-efi78l5tfpp5t4i7ng6h7mhjecvqt4hb.apps.googleusercontent.com',
    iosBundleId: 'com.example.performAi',
  );

}